### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by philipamour** [Carthage/Carthage#1891]
* `carthage version`: latest
* `xcodebuild -version`: latest
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`? 
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 

Tried to compile the project using make install, didn't work. Same with Xcode. See the log below.

** INSTALL FAILED **

The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
make: *** [installables] Error 65

**Comment by ikesyo** [comment]
Should be fixed with #1866.

**Comment by pvaibhav** [comment]
FYI I still have this problem (manual clone + make install, as well as with homebrew), with latest head. I'm on macOS 10.13.
