### ISSUE TITLE
Unable to find iOS Simulators (Post Xcode 10.2 install)

### ISSUE THREAD

**Issue by msaps** [Carthage/Carthage#2691]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: `/usr/local/bin/carthage`
* `carthage version`: 0.31.2
* `xcodebuild -version`: 10.1

After installing Xcode 10.2, Carthage fails to build any project due to `Could not find any available simulators for iOS`. I've tried a number of different things to resolve it:

- Build a project in Xcode 10.2 on a simulator (suggested in #2690)
- Use `Xcode.app` and `Xcode-beta.app`for `xcode-select`.
- Reset all my simulators etc.

I think the problem is the keys that are in the output of `simctl`. Looking through [Simulator.swift](https://github.com/Carthage/Carthage/blob/master/Source/CarthageKit/Simulator.swift) in CarthageKit I can see that it expects to find a platform prefix for the key (i.e. `iOS`) - my keys however are formatted like this: `com.apple.CoreSimulator.SimRuntime.iOS-12-1`.

Is this a problem with my installation? Or is it something that has changed in Xcode 10.2 and should be supported in Carthage?

Example `xcrun simctl list devices --json` output:

```
"com.apple.CoreSimulator.SimRuntime.iOS-12-1" : [
      {
        "availability" : "(available)",
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 5s",
        "udid" : "9AC9332D-7DB0-4F2E-8615-61EE86E363CA",
        "availabilityError" : ""
      },
      {
        "availability" : "(available)",
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 6",
        "udid" : "B1DA5CFF-D918-467B-8E49-04B6172B9456",
        "availabilityError" : ""
      }
]
```

**Comment by blender** [comment]
Are you installing Xcode via MAS or developer portal?

I don't think it's and Xcode 10.2 specific issue but something related to your installation. I have no idea however why something like this would happen.

**Comment by msaps** [comment]
@blender I run the stable version of Xcode through the MAS - I'll try nuking everything and see what if that resolves it. Also maybe avoid the MAS 🤣

**Comment by blender** [comment]
Yeah, I personally don't use MAS and I have never so far encountered issues like this. I don't want to correlated the two but...

**Comment by mattgallagher** [comment]
This type of problem has affected Carthage before. It is not your fault: Carthage needs to be updated to handle the new JSON format used by the Xcode 10.2 beta.

FYI, after encountering the same problem, the issue persisted after reverting to Xcode 10.1. I needed to run:

`xcrun simctl delete unavailable`

to delete unreadable simulators and reset the JSON format.

**Comment by msaps** [comment]
Tried nuking my entire Xcode installation (including `~/Library/Developer/`,`~/Library/Caches/com.apple.dt.Xcode` and the CLI tools), reinstalling 10.1 (from the dev portal) and the Simulator keys are still the same. 

@mattgallagher also tried `xcrun simctl delete unavailable` to no avail, both before and after reinstalling Xcode. 

I'm not sure what causes this format to occur but does seem like something that might be useful for Carthage to handle? What do you think @blender?

**Comment by blender** [comment]
I don't think it's a carthage problem honestly. 

So @msaps you have installed 10.1, ran `xcrun simctl delete unavailable` and now the problem is solved?

This seems to be like it's triggered by installing 10.2. 

I think the right way here is to open a radar and probably and __yet another ad-hoc patch for a non rinal version of Xcode__...

**Comment by taher-mosbah** [comment]
Same problem for me after installing 10.2 via `xcversion` and switching to it using `xcversion select "10.2"` , `xcrun simctl delete unavailable`did not solve the issue.

**Comment by blender** [comment]
try checking what version of `simclt` is actually being invoked

**Comment by msaps** [comment]
@blender unfortunately not. Completely removed my installation, reinstalled 10.1 and the problem still exists. `xcrun simctl delete unavailable` didn't seem to do much and recreating the simulators with Fastlane `fastlane snapshot reset_simulators` also didn't work (both before and after reinstalling Xcode).

`simctl` version: `@(#)PROGRAM:simctl  PROJECT:CoreSimulator-587.24`

**Comment by msaps** [comment]
One potentially interesting point is that I still have the 10.2 Simulator display names in my simulators list (Believe the R and S are rendered differently in <10.2).

<img width="289" alt="screenshot 2019-01-25 at 12 06 08" src="https://user-images.githubusercontent.com/3515448/51742302-a31a3680-2099-11e9-943b-4deea0772075.png">

Unless I missed something stupid, I did remove every Xcode cache/directory I could think of. Had to reinstall the Command Line Tools etc.

**Comment by blender** [comment]
`xcrun simctl --version` on Xcode 10.1 returns `@(#)PROGRAM:simctl  PROJECT:CoreSimulator-581.2`

**Comment by blender** [comment]
@msaps do you have 10.1 CLI tools installed?

**Comment by blender** [comment]
Open 10.1 and run a project on the simulator. 

Now `xcrun simctl list devices --json` will output the format the carthage understands

**Comment by apoltix** [comment]
I am having the same issue. I've checked out Carthage 0.31.2 and run it in Xcode 10.1 to see where it goes wrong, and have found the Simulator class checks the platform's name by prefix (e.g. "iOS"), but the prefix has (seemingly) changed with Xcode 10.2 so it's now "com.apple.CoreSimulator.SimRuntime.iOS-12-2".

After changing `hasPrefix` to `contains` in `Simulator.swift`'s `selectAvailableSimulator` function, it correctly reads the simulators. For some reason they're all marked as `isAvailable = false`, so I'm looking into that now.

**Comment by blender** [comment]
I can reliably switch versions of simctl and reset the output by doing:

- `sudo xcode-select -s /Applications/Xcode_10.1/Contents/Developer`
-  Running any app that boots the simulator
- `xcrun simctl list devices --json`

**Comment by blender** [comment]
please dupe: 

https://openradar.appspot.com/radar?id=5058478808760320

**Comment by blender** [comment]
@msaps did you xcode-select 10.1 ?

**Comment by msaps** [comment]
@blender yeah I was on 10.1 - switching between that and 10.2 didn't seem to make any difference to what `simctl` my machine was using weirdly.

**Comment by apoltix** [comment]
So I've managed to run Carthage 0.32.2 successfully with a single code patch, the aforementioned change of `hasPrefix` to `contains`, building and running from Xcode 10.1 but setting the environment variable `DEVELOPER_DIR` to the Xcode 10.2 beta developer path, e.g. `/Applications/Xcode-beta.app/Contents/Developer`. This makes Carthage use the correct `xcrun` so the simulators are available.

**Comment by msaps** [comment]
@apoltix yeah I'm currently using a locally patched version of Carthage as well.

**Comment by russbishop** [comment]
When Xcode is updated CoreSimulator is updated. CoreSimulator always rolls forward so it will be the version installed by the newest Xcode you ever launched. `simctl` is now bundled with CoreSimulator, that's why you are seeing the newer version.

**Comment by drekka** [comment]
I definitely have the issues where Carthage cannot see any simulators. But also noticed that the Components tab in Xcode 10.2 beta preferences is empty and won't download any.

**Comment by blender** [comment]
@drekka You can patch carthage to do just that like so https://github.com/Carthage/Carthage/issues/2691#issuecomment-457551603

### If you're interested in a little (pointless?) investigation read forward

I have done a little investigation following what @russbishop has said and I found the following.

I am currently using Xcode 9.2 and Xcode 10.2

in Xcode 9.2 `simctl` is at `/Applications/Xcode_9.2.app/Contents/Developer/usr/bin/simctl`

this version links to 
```
/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator (compatibility version 1.0.0, current version 494.33.0)
@rpath/SimulatorKit.framework/Versions/A/SimulatorKit (compatibility version 1.0.0, current version 494.33.0)
```

in Xcode 10.2 instead `simctl` is at `/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Resources/bin/simctl`

this version links to

```
/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator (compatibility version 1.0.0, current version 587.24.0)
/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/Frameworks/CoreSimulatorUtilities.framework/Versions/A/CoreSimulatorUtilities (compatibility version 1.0.0, current version 587.24.0)
```

Now, when I `xcode-select` Xcode 9.2 the "old" (let's call it 9.2 version) version of `simclt` is called from `xcrun` and the opposite when I `xcode-select` Xcode 10.2 

Since the linked version of CoreSimulator is the same and `simctl 9.2` and `simctl 10.2` both use a common subset of the CoreSimulator API (the other frameworks look inconsequential) __I believe this is a bug in `simctl 10.2`__. In fact unsurprisingly if I replace `simctl 10.2` with a simlink to `simctl 9.2` an xcode-select Xcode 10.2 carthage works just fine.

**Comment by mdiep** [comment]
I think we need to suck it up and update our use of the JSON format.

These seemingly random JSON changes from the simulator team are extremely disappointing. This is 2nd Xcode release in a row that includes a breaking change to the JSON API—with no mention in the release notes and seemingly with no reason for it.

I assumed that the point of JSON output was easier consumption by tooling. But these breaking changes make it worse for tooling, not better. It makes me regret switching to the JSON output at all. We would have been better off parsing the normal output since it hasn't changed.

**Comment by Nonnus** [comment]
@mdiep from your words I assume we need to wait for a Carthage update to fix the issue and allow use of Xcode 10.2?

**Comment by mdiep** [comment]
Yup!

**Comment by drekka** [comment]
Thanks @blender I've downloaded the Carthage source with a view to taking a look, but I'm having problems working with it. Could be an issue with 10.2 as well. Who knows.

**Comment by dive** [comment]
Btw, it seems that Apple removed all previous simulator runtimes support from Xcode 10.2b. Perhaps, due to missing dynamically linked libraries for the Swift standard library. I tried to link them manually, but it didn't work to me. I didn't try hard though.
I mean, you'll see the following information if you switch to Xcode 10.2b with `xcode-select` and try to list the simulators:
```bash
$ xcrun simctl list devices --json | grep -A16 12.1
    "com.apple.CoreSimulator.SimRuntime.iOS-12-1" : [
      {
        "availability" : "(unavailable, runtime profile not found)",
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 5s",
        "udid" : "DDD36346-A76F-42E8-80F4-6F11E1EE4BEB",
        "availabilityError" : "runtime profile not found"
      },
      {
        "availability" : "(unavailable, runtime profile not found)",
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 6",
        "udid" : "21794717-BC89-45E4-9F57-8CF9D14A87D1",
        "availabilityError" : "runtime profile not found"
      },
...
```

No runtime for `com.apple.CoreSimulator.SimRuntime.iOS-12-1` at all.

**Comment by blender** [comment]
🥁 

>Apple Developer Relations
> Please know that our engineering team has determined that this issue behaves as intended based on the information provided.
> In order to better support pinning, this was the least disruptive option.

**Comment by qnoid** [comment]
What do they mean by pinning?

**Comment by shinma** [comment]
It's not that hard to change one line in `Simulator.swift`.
```
let platformName = sdk.platform.rawValue
	let platformName = "com.apple.CoreSimulator.SimRuntime.\(sdk.platform.rawValue)"
```
...and it works.

**Comment by taher-mosbah** [comment]
Now that #2693 is merged does it make sense to have a release ? 
or should we wait for finale version of Xcode 10.2 ?

**Comment by Nonnus** [comment]
hopefully we won't have to wait for any final version of Xcode 10.2 as this would be terribly disruptive to ongoing testing and development that should be done before the final release

**Comment by yapiskan** [comment]
This issue is currently breaking our buddybuild CI builds. Would be great if there would be a release.

**Comment by mvnevesbrb** [comment]
Please, do you have a solution for this problem ? Or can you point how can I compile the source, because some packages :

error: dependency graph is unresolvable; found these conflicting requirements:

Dependencies:
    https://github.com/jdhealy/PrettyColors.git @ 5.0.0..<6.0.0
    https://github.com/thoughtbot/Curry.git @ 4.0.0..<5.0.0
'Carthage' ... error: product dependency 'Curry' not found
'Carthage' ... error: product dependency 'PrettyColors' not found
'Carthage' ... error: product dependency 'Curry' not found

**Comment by mvnevesbrb** [comment]
> It's not that hard to change one line in `Simulator.swift`.
> 
> ```
> let platformName = "com.apple.CoreSimulator.SimRuntime.\(sdk.platform.rawValue)"
> ```
> ...and it works.
> 
> OR...
> 
> ```
> let allTargetSimulators = devices.filter { $0.key.stripping(prefix: "com.apple.CoreSimulator.SimRuntime.").hasPrefix(platformName) }
> ```
> ...with backward compatibility.

how did you achieve to compile the code, can you help?

**Comment by shinma** [comment]
> > It's not that hard to change one line in `Simulator.swift`.
> > ```
> > let platformName = "com.apple.CoreSimulator.SimRuntime.\(sdk.platform.rawValue)"
> > ```
> > ...and it works.
> > OR...
> > ```
> > let allTargetSimulators = devices.filter { $0.key.stripping(prefix: "com.apple.CoreSimulator.SimRuntime.").hasPrefix(platformName) }
> > ```
> > ...with backward compatibility.
> 
> how did you achieve to compile the code, can you help?

- ```git checkout 0.31.2```
- ```make boostrap```
- open Carthage.workspace
- build using Xcode 10.1
- ```make install``` to replace brew version (after fix is released ```make uninstall``` and ```brew upgrade```)

**Comment by jdhealy** [comment]
Fixes released with https://github.com/Carthage/Carthage/releases/tag/0.32.0

〜 Hold tight for a Homebrew release: [submitted for PR](https://github.com/Homebrew/homebrew-core/pull/36614).

Thanks @kmcbride and @DavidBrunow for submitting fixes!

Thank you to @giginet, @taher-mosbah, @ikesyo, and @blender for reviewing pull requests!

**Comment by kaushal9678** [comment]
if could not found simulator still persists after replacing following lines of code in runSimulator.js

`if (!version.startsWith('iOS') && !version.startsWith('tvOS')) {
     continue;
   }
`

with this one 

`
if (
      !version.startsWith('com.apple.CoreSimulator.SimRuntime.iOS') &&
      !version.startsWith('com.apple.CoreSimulator.SimRuntime.tvOS')
    ) {
      continue;
    }
`

comment following lines after replacing 

`
if (
        simulator.availability !== '(available)' &&
        simulator.isAvailable !== 'YES'
      ) {
        continue;
      }
`
It will launch iPhone simulator without any issue.

**Comment by RustamKhisamov** [comment]
> @blender unfortunately not. Completely removed my installation, reinstalled 10.1 and the problem still exists. `xcrun simctl delete unavailable` didn't seem to do much and recreating the simulators with Fastlane `fastlane snapshot reset_simulators` also didn't work (both before and after reinstalling Xcode).
> 
> `simctl` version: `@(#)PROGRAM:simctl PROJECT:CoreSimulator-587.24`

helps me with Xcode 11 beta

**Comment by rsalunga29** [comment]
If you are experiencing this in Xcode 11 and was surprised that iPhone X is not on the list of the new iOS 13.0 simulators, I think this should explain it all.

"Xcode no longer creates every available iOS simulator device by default. Instead a set of the most commonly used devices are created. To create other devices — or multiple instances of a device — open the Devices window, select Simulators, click the + button, enter a name, and select the relevant device type and OS version. In Terminal, execute the xcrun simctl create <name> <device type> <OS version> command, for example xcrun simctl create "My iPhone 7" "iPhone 7" iOS13.0. (49428617)"

Reference: https://developer.apple.com/documentation/xcode_release_notes/xcode_11_release_notes
