### ISSUE TITLE
Nondeterministic “project has no shared schemes” error

### ISSUE THREAD

**Issue by truppelito** [Carthage/Carthage#299]
I wanted to use Carthage on a new app I'm developing so I created a dummy Xcode project just to try it out. Inside the dummy project folder (where the xcodeproj file is) I added a Cartfile with this in it:

```
github "robb/Cartography"
github "kishikawakatsumi/KeychainAccess"
github "Alamofire/Alamofire"
github "SwiftyJSON/SwiftyJSON"
github "hubertr/Swell"
```
(all these projects say they are Carthage compatible, btw)

Then I ran on Terminal:

    cd /path/to/folder/containing/dummy/xcodeproj
    carthage update

Sure enough a `Carthage.resolved` file is created which contains this:

```
github "Alamofire/Alamofire" "1.1.4"
github "robb/Cartography" "0.2.0"
github "kishikawakatsumi/KeychainAccess" "v1.1.1"
github "hubertr/Swell" "1.0.1"
github "SwiftyJSON/SwiftyJSON" "2.1.3"
```

And a Carthage folder is created. Inside are the Build and Checkouts folders. The Checkouts folder contains 5 subfolders (one for each project), as expected. My problem is that the Build folder is totally and completely empty!

Here is the output produced by `carthage update`:
```
*** Fetching Cartography
*** Fetching KeychainAccess
*** Fetching Alamofire
*** Fetching SwiftyJSON
*** Fetching Swell
*** Checking out Alamofire at "1.1.4"
*** Checking out Cartography at "0.2.0"
*** Checking out KeychainAccess at "v1.1.1"
*** Checking out Swell at "1.0.1"
*** Checking out SwiftyJSON at "2.1.3"
*** xcodebuild output can be found in /var/folders/7p/r8sw1dw15ks2_pcb0tbm5lkw0000gn/T/carthage-xcodebuild.bBK0SN.log
Project "Alamofire.xcodeproj" has no shared schemes
```

The xcodebuild output file is completely empty, and the error (`Project "Alamofire.xcodeproj" has no shared schemes`) is not correct. If I go to the Alamofire folder inside the Checkouts folder and open that xcodeproj file and check the schemes it contains I can see that it has two shared schemes (one for iOS and one for Mac).

Am I doing something wrong? Thanks.

**Comment by mdiep** [comment]
Can you check which version of carthage you're running with `carthage version`?

**Comment by truppelito** [comment]
Yes, of course, `carthage version` outputs: 0.5.2.

**Comment by jspahrsummers** [comment]
Hmm, I can't reproduce this. I tried with a Cartfile containing just:

```
github "Alamofire/Alamofire" == 1.1.4
```

… as well as the exact Cartfile you specified above. In both cases, Alamofire started building without issue:

```
*** Cloning Cartography
*** Cloning KeychainAccess
*** Fetching Alamofire
*** Fetching SwiftyJSON
*** Fetching Swell
*** Checking out Alamofire at "1.1.4"
*** Checking out Swell at "1.0"
*** Checking out Cartography at "0.2.0"
*** Checking out KeychainAccess at "v1.1.1"
*** Checking out SwiftyJSON at "2.1.3"
*** xcodebuild output can be found in /var/folders/bc/94873c7x4b97j9kczw008fh40000gn/T/carthage-xcodebuild.ZRHgVO.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
```

Can you please try `rm -rf ~/Library/Caches/org.carthage.CarthageKit` and attempt `carthage update` again?

**Comment by truppelito** [comment]
Nope, doesn't work:
```
$ rm -rf ~/Library/Caches/org.carthage.CarthageKit
$ carthage update
*** Cloning Cartography
*** Cloning KeychainAccess
*** Cloning Alamofire
*** Cloning SwiftyJSON
*** Checking out Alamofire at "1.1.4"
*** Checking out Cartography at "0.2.0"
*** Checking out KeychainAccess at "v1.1.1"
*** Checking out SwiftyJSON at "2.1.3"
*** xcodebuild output can be found in /var/folders/7p/r8sw1dw15ks2_pcb0tbm5lkw0000gn/T/carthage-xcodebuild.sAYRoC.log
Project "Alamofire.xcodeproj" has no shared schemes
```
The `Build` folder has nothing in it, and the `xcodebuild` log is empty.
I don't know if that matters, but I have Xcode 6.2 beta 5 installed.

**Comment by truppelito** [comment]
Interestingly, if I have the Cartfile with only:

    github "Alamofire/Alamofire" == 1.1.4

Then it works!
```
$ rm -rf ~/Library/Caches/org.carthage.CarthageKit
$ carthage update
*** Cloning Alamofire
*** Checking out Alamofire at "1.1.4"
*** xcodebuild output can be found in /var/folders/7p/r8sw1dw15ks2_pcb0tbm5lkw0000gn/T/carthage-xcodebuild.2720LM.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire OSX" in Alamofire.xcworkspace
```
And the `Build` folder has the correct results.

**Comment by truppelito** [comment]
And there's more! If I omit the version information from the Cartfile:

    github "Alamofire/Alamofire"

It doesn't work anymore:
```
$ rm -rf ~/Library/Caches/org.carthage.CarthageKit
$ carthage update
*** Cloning Alamofire
*** Checking out Alamofire at "1.1.4"
*** xcodebuild output can be found in /var/folders/7p/r8sw1dw15ks2_pcb0tbm5lkw0000gn/T/carthage-xcodebuild.E2p84J.log
Project "Alamofire.xcodeproj" has no shared schemes
```

**Comment by truppelito** [comment]
And just to finish all the possibilities, these lines also work (tested separately, in the same way as before):

github "Alamofire/Alamofire" >= 1.1.4
github "Alamofire/Alamofire" ~> 1.1.4

**Comment by jspahrsummers** [comment]
That's super weird. In the broken checkout, what happens if you run:

```sh
xcodebuild -list -project Alamofire.xcodeproj
```

Also, for the hell of it, can you please share `xcodebuild -version`?

**Comment by truppelito** [comment]
```
$ xcodebuild -version
Xcode 6.1.1
Build version 6A2008a
```

Actually, since my last post I updated Carthage to 0.5.3 and the initial Cartfile (various repos and no version constraints) is now working perfectly:

$ rm -rf ~/Library/Caches/org.carthage.CarthageKit
$ carthage update
*** Cloning Cartography
*** Cloning KeychainAccess
*** Cloning Alamofire
*** Cloning SwiftyJSON
*** Checking out Alamofire at "1.1.4"
*** Checking out SwiftyJSON at "2.1.3"
*** Checking out KeychainAccess at "v1.1.1"
*** Checking out Cartography at "0.2.0"
*** xcodebuild output can be found in /var/folders/7p/r8sw1dw15ks2_pcb0tbm5lkw0000gn/T/carthage-xcodebuild.wOFr5K.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire OSX" in Alamofire.xcworkspace
*** Building scheme "Cartography-iOS" in Cartography.xcodeproj
*** Building scheme "Cartography-Mac" in Cartography.xcodeproj
*** Building scheme "KeychainAccess-iOS" in KeychainAccess.xcworkspace
*** Building scheme "KeychainAccess-Mac" in KeychainAccess.xcworkspace
*** Building scheme "SwiftyJSON" in SwiftyJSON.xcworkspace

I'm sure it was just a glitch in the Matrix. Thanks for your time!

**Comment by jspahrsummers** [comment]
No problem. Glad it's working now!

**Comment by jspahrsummers** [comment]
@bavarious is [seeing this](https://gist.github.com/bavarious/533a08f91ea5f1c523ba) intermittently on 0.6.2.

**Comment by truppelito** [comment]
I concur. I forgot to reopen this issue, but I'm also seeing this again, and this time providing version constraints is not solving it.

**Comment by jspahrsummers** [comment]
@truppelito @bavarious Those times you saw this error, did it take several seconds for it to appear, or did it appear instantly after logging the lines before?

**Comment by bavarious** [comment]
@jspahrsummers Instantly. I suspect this might be related to how stdout/stderr are being parsed.

I’ll try to set up a debug environment this weekend.

**Comment by samritchie** [comment]
I just hit this as well trying to run `carthage bootstrap` on a fresh carthage 0.6.4 install on a CI server. 
Alamofire was the culprit in this case also - Cartfile.resolved lists `github "Alamofire/Alamofire" "1.1.5"`

`xcodebuild -list` returned the following:

    Information about project "Alamofire":
    Targets:
        Alamofire iOS
        Alamofire OSX
        Alamofire iOS Tests
        Alamofire OSX Tests

    Build Configurations:
        Debug
        Release

    If no build configuration is specified and -scheme is not passed then "Release" is used.

    Schemes:
        Alamofire iOS
        Alamofire OSX

I ran it a second time and it worked. I did open Alamofire in Xcode between the two attempts (to check it had shared schemes) - this may or may not have been significant.

**Comment by jspahrsummers** [comment]
@samritchie Thanks! I think it was just coincidence, unfortunately, based on the nondeterministic nature of this bug.

@bavarious’ hunch about stdout/stderr sounds plausible, since we could possibly be terminating our stream reading before we've hit EOF.

**Comment by bavarious** [comment]
I’ve set up a test environment and saw this bug upon running Homebrew’s 0.6.4 `carthage`. Then I cleaned up my environment with
````
rm -rf Cartfile.resolved \
    Carthage \
    ~/Library/Caches/org.carthage.CarthageKit \
    ~/Library/Caches/carthage
````
just to be sure. I reproduced the error in Xcode a couple of times, and then never again for ~20 tries using both the Debug and the Release configurations. Went back to Homebrew’s `carthage` and wasn’t able to reproduce it.

Sneaky, sneaky.

I’ll take a look at this again tomorrow.

**Comment by bavarious** [comment]
An example output that leads to the bug:
![bug](https://cloud.githubusercontent.com/assets/531537/7103167/fd26dccc-e070-11e4-82b6-43ab7c3bce31.png)

**Comment by bavarious** [comment]
This is what I’ve found so far:

 * It is a timeout issue. I created another Carthage error for this case to make sure that Carthage is timing out;
 * I’ve timed `xcodebuild -list` and sometimes (rarely) it approaches four seconds of total time;
 * Xcode indexing waits for any xcodebuild invocation to complete. If I launch `xcodebuild -list` whilst Xcode is indexing a workspace that’s not related to the project being listed, Xcode waits for that xcodebuild invocation to complete before resuming indexing and the total time of `xcodebuild -list` increases more frequently.

My suggestion is to increase the timeout.

Also, currently the NoSharedSchemes error is used when xcodebuild explicitly says there are no schemes or if there is a timeout. Since we’re hitting timeout in two possible cases: there are no schemes and xcodebuild hangs, or there are schemes but xcodebuild is taking too long to execute, maybe we should create another Timeout error and output a different error message from NoSharedSchemes.

**Comment by jspahrsummers** [comment]
@bavarious Both of those suggestions sound great. :+1:

**Comment by jspahrsummers** [comment]
Hopefully fixed by #423. :pray:

**Comment by julianshen** [comment]
It still happens to me while I trying to build my project with ReactiveCocoa using 0.6.5. I tried to "cd Carthage/Checkouts/ReactiveCocoa/" and did "carthage update" there. Another error happened: "Not a valid object name: 'master'" to "Quick/Quick". I found this is because my git version was very old (1.7). After I updated my git, All problem solved (including this "timeout" problem). Is that possible xcodebuild encounter an error and does not log to the log file? If it's this case, might never know the real problem to solved and timeout might still happen.

**Comment by jspahrsummers** [comment]
@julianshen It sounds like you're encountering a different problem, since the error message is different. If you believe it's a bug in Carthage, could you please open a separate issue?

**Comment by julianshen** [comment]
Sorry, I did not explain it clearly. Actually, the error message is the same. (“project has no shared schemes”). The message I posted is when I tried to build ReactiveCocoa in project separately. Might be another issue. Both of these two solved when I upgrade my git.

**Comment by julianshen** [comment]
Reverted my git and tested it again. This should be different issue. My symptom is more like #400 . Sorry about the mistaken.

**Comment by jinthagerman** [comment]
I am getting this timeout, but I'm unsure why. 

````xcodebuild -list```` returns immediately when I run it manually on the checked out project. I'm on Carthage 0.8.0. Any ideas?

**Comment by jinthagerman** [comment]
Ok, so I've figured out why I was hitting this timeout. There was an issue with Xcode 7 beta 1 where on first run, it would install like 100+ simulators for some reason. I cleared these out and I'm no longer hitting the timeout.

**Comment by amccarri** [comment]
I'm seeing this on carthage 0.14.0, el-cap 10.11.3, Xcode 7.2.1 (7c1002) when trying to add a dependency on libextobjc framework.  I've tried all the suggestions in this issue and nothing has worked.

**Comment by jspahrsummers** [comment]
@amccarri As mentioned in https://github.com/jspahrsummers/libextobjc/issues/108#issuecomment-187961659, that's nothing to do with Carthage, and it's very deterministic.
