### ISSUE TITLE
Issues with 0.7.1 version

### ISSUE THREAD

**Issue by zocario** [Carthage/Carthage#445]
I am having multiple issues since I have updated to latest version (0.7.1).
First I have the same issue as #444 but even if I delete Realm from my Cartfile I am still having strange behavior as Fetching or Checking out that never ends, or permissions denied errors.

My Cartfile is very simple:

    github "Alamofire/Alamofire"
    github "Hearst-DD/ObjectMapper"

Here is an example of permission error I had:

![capture d ecran 2015-05-08 a 13 15 27](https://cloud.githubusercontent.com/assets/800617/7535375/a9683260-f584-11e4-929f-05faf6213ce3.png)

After deleting Carthage folder and Cartfile.resolved file, I am stuck on ```Fetching``` step, but before it was the case for the ```Checking out``` step:

![capture d ecran 2015-05-08 a 13 24 11](https://cloud.githubusercontent.com/assets/800617/7535456/8e30a760-f585-11e4-8707-d41d7b8e0876.png)

Is there any known issues about this? 
What can I do to give you more informations to solve this problem?

Since this morning I am not able to retrieve dependencies for my new project.

**Comment by MichaelMcGuire** [comment]
I'm having the same problem and was about to open another issue.  I'd like to try to diagnose this myself, but I'm having a hard time figuring out how to run a debug version of Carthage.  My Cartfile:

````
github "ReactiveCocoa/ReactiveCocoa" "swift-development"
github "thoughtbot/Argo" "master"
github "AliSoftware/OHHTTPStubs"
github "danielgindi/ios-charts" "master"

github "Quick/Quick"
github "Quick/Nimble"
````

and the output is stuck on Result running `carthage update`
````
$ carthage update
*** Fetching Nimble
*** Fetching Quick
*** Fetching ios-charts
*** Fetching OHHTTPStubs
*** Fetching Argo
*** Fetching ReactiveCocoa
*** Fetching Box
*** Fetching Runes
*** Fetching Result
````
If I delete the cache in ` /Users/user/Library/Caches/org.carthage.CarthageKit` and try the command again, it gets stuck on cloning Result:
````
$ carthage update
*** Cloning Nimble
*** Cloning Quick
*** Cloning ios-charts
*** Cloning OHHTTPStubs
*** Cloning Argo
*** Cloning ReactiveCocoa
*** Cloning Box
*** Cloning Runes
*** Cloning Result
````
Started happening after upgrading Carthage yesterday via homebrew.

**Comment by mdiep** [comment]
Do you know which version you upgraded from?

**Comment by MichaelMcGuire** [comment]
For me, I'm pretty sure it was 0.6.

**Comment by zocario** [comment]
It was from 0.7 for me, and I also had issues with 0.7 after upgrade. I think it was related to realm as I didn't try to remove realm from my Cartfile before 0.7.1.

**Comment by mdiep** [comment]
This sounds like a dupe of #219.

**Comment by MichaelMcGuire** [comment]
In my case, I'm only accessing public repos and haven't had this problem before.

**Comment by zocario** [comment]
Same, but as last comment in this issue has the same problem with public repo it sounds like a dupe...

**Comment by MichaelMcGuire** [comment]
I'd love to try debugging Carthage to see if I can figure out what is hanging, but I can't find any instructions or guidance on launching Carthage from Xcode.  If someone can help out with that, I'd love to try debugging.  Thanks!

**Comment by pizthewiz** [comment]
I don't have much to add except I also upgraded from 0.7.0 to 0.7.1 via homebrew this morning, my Cartfile only contains public repos and deleting the cache didn't seem to help.

Strangely I'm unable to manually clone https repos in the terminal, it always comes back that my username or password is invalid - I'm not sure why my credential cache was flushed along with upgrading to 0.7.1, but perhaps just odd timing?

**Comment by KyleLeneau** [comment]
Not sure if this is related but using 0.7.1 I am not getting prompted for my username when trying to clone dependencies of ReactiveCocoa.

Here is my Cartfile

    github "ReactiveCocoa/ReactiveCocoa" "v3.0-beta.4"
    github "realm/realm-cocoa"
    github "smileyborg/PureLayout"

Here is my output now:

    $ carthage update
    *** Fetching PureLayout
    *** Fetching realm-cocoa
    *** Fetching ReactiveCocoa
    *** Fetching Result
    *** Fetching Box
    Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com':

**Comment by mdiep** [comment]
As of 0.7.1, Carthage will try to use the authenticated GitHub.com API to work around rate-limiting issues. That's why you've started seeing this issue for public repositories.

**Comment by KyleLeneau** [comment]
Hmm, anyway around it then or ability for me to pass my username and password with the update for the API calls?

**Comment by mdiep** [comment]
I think everything should work if you follow the instructions [here](https://github.com/Carthage/Carthage/issues/219#issuecomment-94166964).

**Comment by pizthewiz** [comment]
My manual cloning issue was self-inflicted password vs personal access token. Resolving that and blowing away the cache, `carthage update` was able to proceed.

**Comment by pizthewiz** [comment]
Even after fixing the auth issue, the `carthage` command usually hangs at various points, are the GitHub API requests getting silently throttled and the command is waiting to retry?

**Comment by mdiep** [comment]
Carthage should immediately try again without credentials if an authenticated request fails. I'm not sure why it would be hanging.

**Comment by MichaelMcGuire** [comment]
I switched back to 0.6.2 and everything is working fine.  I'm going to try 0.7 from a connection not behind a proxy to see if there is something going on there.

**Comment by pizthewiz** [comment]
I hadn't seen this hanging behavior until I updated to 0.7.1 - the `--verbose` switch doesn't work with `update`, is there another way I can provide some further info?

**Comment by tonyarnold** [comment]
I think my #447 might be a dupe of this issue. 0.7.1 is pretty broken for me :(

**Comment by elliottsj** [comment]
Here's my workaround for now:

1. Install and enable the [git caching credential helper](https://help.github.com/articles/caching-your-github-password-in-git/).
2. **If you use 2-factor authentication:** Create a [personal access token](https://github.com/settings/tokens), copy it to your clipboard.
3. Attempt a `git push` to any GitHub HTTPS remote. Git will ask for your GitHub username & password; **if using 2FA, paste your personal access token as the password**.

    Regardless of whether or not the push succeeded, your password/access token should now be cached on your machine.
4. Now try `carthage update`; when Carthage fetches from GitHub, it should use your cached password/access token.

**Comment by jspahrsummers** [comment]
I agree this is a serious bug in Carthage, and I apologize to everyone experiencing it!

Unfortunately, I'll be unavailable for a few days (bad timing). If nobody else in @Carthage/carthage is around to apply a fix, I'd recommend that anyone affected download and install [0.7](https://github.com/Carthage/Carthage/releases/tag/0.7) or [0.6.5](https://github.com/Carthage/Carthage/releases/tag/0.6.5) until we can create a proper fix.

Sorry again about the trouble! :heart:

**Comment by mdiep** [comment]
0.7.2 was released, which should fix this issue for anyone using Xcode 6.3+.

**Comment by zocario** [comment]
@mdiep I've just updated to 0.7.2 and I am still having the same issue...
I've deleted Carthage cache but still stuck at Cloning or Fetching step.

When I clone an https private repository, I have no prompt for my password so I don't understand why it is not working. Is there something I should do before 0.7.2 works?

Rolled back again to 0.6.5 and no problems.

**Comment by robrix** [comment]
0.7.3 has been released and I am just submitting it to homebrew now.

**Comment by robrix** [comment]
[Submitted](https://github.com/Homebrew/homebrew/pull/39677).

**Comment by zocario** [comment]
Hi @robrix I've downloaded the released version of 0.7.3 and I'm still having the issue...

**Comment by mdiep** [comment]
@zocario Can you post your cartfile and the output after using 0.7.3? Also, can you double check that you're using 0.7.3 by running `carthage version`?

**Comment by zocario** [comment]
Already done for ```carthage version``` it is 0.7.3.
My cartfile is:

    github "Alamofire/Alamofire"
    github "Hearst-DD/ObjectMapper"

My git version is ```2.3.2 (Apple Git-55)```, I don't know if it helps.
I've checked if my credentials were correctly stored for Github by Cloning private repo or pushing changes and everything is fine.

Is there something else I can try?

**Comment by mdiep** [comment]
@zocario What's the output of `carthage update`?

**Comment by zocario** [comment]
![capture d ecran 2015-05-12 a 19 10 44](https://cloud.githubusercontent.com/assets/800617/7593460/a6949b10-f8da-11e4-8c33-799e4b718234.png)

**Comment by ikesyo** [comment]
I confirmed that `carthage checkout`, `carthage bootstrap` works, but `carthage update` does not...

**Comment by robrix** [comment]
I have a (partial, bad) solution to this but it’s going to take me longer to polish it off. I believe the basic issue is that `ReactiveTask` is flooding the global queue with as many reads/writes as it can. `libdispatch` does not like that.

**Comment by delba** [comment]
I am experiencing the same issue since I upgraded to `0.7.X`.
- It's pretty random: it gets stuck either during the `Fetching`, the `Checking out` or the `Building scheme` steps.
- The `carthage build` command always succeed.
- Removing `Carthage/`, `Cartfile.resolved` and `~/Library/Caches/org.carthage.CarthageKit/` didn't help.

Here is the output of multiple `carthage update` using `carthage 0.7.3`: https://gist.github.com/delba/138e0ce9be224f6c3229

**Comment by jspahrsummers** [comment]
This should be fixed by #474. I'd greatly appreciate anyone who's willing to test [0.7.4-beta.1](https://github.com/Carthage/Carthage/releases/tag/0.7.4-beta.1) on their projects! :bow:

**Comment by tonyarnold** [comment]
_Seems_ to have fixed the issues for me. I've run update with carthage HEAD against a few different projects, and it worked each time. I think you might be there, JSS! :clap:

**Comment by delba** [comment]
It fixed the issue :smile: Thanks a lot!

**Comment by derrh** [comment]
:+1:

**Comment by derrh** [comment]
Sorry to amend my :+1:. I'm getting a segfault on copy-frameworks now.

    /Users/derrick/Library/Developer/Xcode/DerivedData/Canvas-hhhulncsfqdqyhdzbhuorwtukncl/Build/Intermediates/iCanvas.build/Debug-iphonesimulator/iCanvas.build/Script-6161E4AF1B02584F0056E368.sh: line 2: 32464 Segmentation fault: 11  /usr/local/bin/carthage copy-frameworks
    Command /bin/sh failed with exit code 139

Would more data be helpful?

**Comment by delba** [comment]
@derrh Removing the DerivedData directory solved the issue for me

**Comment by jspahrsummers** [comment]
@derrh Could you please open Console.app and find the “User Diagnostic Reports” available from Carthage, which should have the backtrace? :pray:

**Comment by derrh** [comment]
Not sure the best way to attach a crash log. How's this? https://gist.github.com/derrh/9ff61095c334ce3c2d32

Thanks, Justin!

**Comment by zocario** [comment]
Hi guys, I've just tested this new version, and I am also having a segmentation fault error:
![capture d ecran 2015-05-27 a 19 32 04](https://cloud.githubusercontent.com/assets/800617/7842994/19286e54-04a7-11e5-9351-3d63fa7ef18a.png)

Here is the associated crash log file:
https://www.dropbox.com/s/hm8k2i0wpdspo91/carthage.crash?dl=0

Thanks!

**Comment by jspahrsummers** [comment]
Segfaulting should be fixed in [0.7.4-beta.2](https://github.com/Carthage/Carthage/releases/tag/0.7.4-beta.2).

**Comment by Goles** [comment]
@jspahrsummers what's the simplest way to install a beta version of Carthage?

**Comment by jspahrsummers** [comment]
There's a `.pkg` installer attached to each release that you can use.
